name: Tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build for Windows
      run: |
        cargo install --path tools --root install --verbose
    - name: Archive Windows build
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: install/bin
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build for Linux
      run: |
        cargo install --path tools --root install --verbose
    - name: Archive Linux build
      uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: install/bin
